### ISSUE TITLE
npx percy snapshot -c <config> ignores static-snapshots hash

### ISSUE THREAD

**Issue by poolski** [percy/percy-agent#393]
When running `npx percy snapshot` with the config file parameter, the `static-snapshots` hash is ignored entirely, meaning that if you want to add some paths to be tested or ignored, you *have* to set them as CLI flags, which gets unwieldy very quickly.

Given a config like this:

```
{
    "version": 1,
    "snapshot": {
        "widths": [
            1280
        ]
    },
    "static-snapshots": {
        "path": "_site/",
        "ignore-files": "node_modules/**/*,learn/**/*,updates/**/*",
        "snapshot-files": "updates/*,policies/*,/contact-us/*"
    }
}
```

`npx percy snapshot` picks up the `snapshot` hash with the `widths` parameter but `path`, `ignore-files` and `snapshot-files` are all ignored.

When you do the same thing with `percy exec -- <thing>` then the parameters are actually picked up. This seems really inconsistent.

**Comment by wwilsman** [comment]
Recent config changes removed a nasty bug where we were previously, accidentally, mutating the default config object when loading from a config file. This caused the CLI flags to default to the config file contents rather than their intended defaults, and it hid this bug from being detected due to our old tests testing against the mutated default config object incorrectly.

What's happening to cause this, is the CLI flags always take precedence over config file options. But the CLI flags are defaulting to their intended defaults, therefore the defaults are overriding your config file.

I'm going to release a change soon that will strip these defaults before overriding file options with flag options. I also noticed that the `path` option is required in the CLI even though it does have a default, so I'm going to remove that requirement as well.

I'll update this issue once that's released 🙂

**Comment by wwilsman** [comment]
> I'll update this issue once that's released

Completely dropped the ball here. This should be fixed in the latest version. 👍
