### ISSUE TITLE
Remove puppeteer dependency

### ISSUE THREAD

**Issue by newtack** [percy/percy-agent#452]
When having puppeteer as a dependency, yarn either takes a very long time or hangs. That's why we switched to using puppeteer-core. After adding this library yarn hang again because of puppeteer. 
Can you make the dependency to puppeteer at least optional or change it to puppeteer-core instead?

For now this is a showstopper for using Percy.

**Comment by Robdel12** [comment]
Hey @newtack! If you have an instance of Chrome locally you can skip the download: https://docs.percy.io/docs/skipping-puppeteer-chromium-download

**Comment by newtack** [comment]
I don't think this answer is related to my question. I am already doing this in the actual test.

My test does not have a dependency to puppeteer, your library has. So when running yarn (before any test even runs), it tries to install puppeteer.

**Comment by Robdel12** [comment]
> My test does not have a dependency to puppeteer, your library has. So when running yarn (before any test even runs), it tries to install puppeteer.

Correct, Percy Agent will always require Puppeteer to work. If you already have a Chrome binary on your system (CI, locally, etc), you can supply the path (`PUPPETEER_EXECUTABLE_PATH`) and also set `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true`. More here: https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#environment-variables

If you don't have Chrome locally available, you will have to let the Puppeteer package download the executable. Otherwise there's no way to use this package.
