### ISSUE TITLE
Percy support for non http(s) protocols?

### ISSUE THREAD

**Issue by sagaru** [percy/percy-agent#487]
Hello, 

We integrated Percy in our webdriverIO project, we are currently getting this error

`[percy] StatusCodeError 400 - {"errors":[{"status":"bad_request","detail":"Invalid URL, scheme must be http or https: chrome-extension://**********/content/popup/index.html"}]}`

Does anyone have a clue on how to fix this?

**Comment by wwilsman** [comment]
Our asset discovery service will work fine with chrome extensions but will fail with firefox extensions. Short of implementing a firefox discovery service, we could transform the extension protocol into a supported protocol. I'll have to experiment with this next week to see if it's feasible and still works in our asset discovery service. But once the protocol is transformed into a supported one, our API should no longer throw that error.

🤔

**Comment by sagaru** [comment]
That'd be a great help for us @wwilsman 👍 
Looking forward to it 😊

**Comment by Robdel12** [comment]
Just to be clear, what we would probably do is replace `chrome-extension://` & `moz-extension://` with `http://localhost` & run the DOM snapshot through. Asset discovery & our browsers will treat this as a normal web page (so there's no extension specific things that will be supported, if it's needed).

Would that solve what you're looking to do? You'll probably have to configure a Percy project for each browser and render each extensions DOM snapshots in their respective browser

**Comment by sagaru** [comment]
@Robdel12 it could be great if you could do that, it can still be useful in many scenarios. 

In some cases, to display some items we rely on extension-specific communications via Extension APIs. We can rely on screenshots for those.

**Comment by sagaru** [comment]
@Robdel12 @wwilsman Any update on this?

**Comment by wwilsman** [comment]
Hi @sagaru, sorry for the late response on this.

We can't transform the protocol before asset discovery, otherwise assets won't be discovered. Due to this, we could only possibly work with Chrome extensions and not Firefox extensions at all. Even then, we would still need to transform the protocol before it gets to the API after assets are discovered.

I'm not sure if I would consider that adding "support" or more of a hack to work around the error for Chrome extensions specifically. Because even with that transformation, there is no guarantee that assets will be requested without their protocol. If they are requested with a protocol, that snapshot would fail causing the whole build to fail. Furthermore, the extension APIs one might expect to be present will not exist on our servers when we re-render, adding even more limitations to this approach.

Sorry to say, but I don't think we'll be able to support this officially without having our infrastructure able to fully support it. I know you are using this workaround already, but to others stumbling upon this issue, you'll have to take your own screenshots of the extension in your tests and then send those screenshots up to Percy for diffing using the [upload command](https://docs.percy.io/docs/command-line-client#section-percy-upload-uploaddirectory).
